// Windissect exhaustive candidate class surface for StartMenuExperienceHost.exe.
// Experimental: declarations may contain unresolved PDB language ambiguities.
#pragma once

#include "windissect_abi.h"
#include "windissect_forwards.h"
#include "windissect_vcalls.h"
#include "windissect_calls.h"
#include "utilities/Details_8b808a4f1cd7d1dc.h"
#include "utilities/abi_FTMWeakRefData.h"
#include "utilities/ModuleBase.h"
#include "utilities/EventSource.h"
#include "utilities/LaunchExperience.h"
#include "utilities/InProcModule.h"
#include "utilities/winRT.h"
#include "utilities/Details_768150bc3cb23cbf.h"
#include "utilities/abi_CaptureBase.h"
#include "utilities/ExperienceHostLogging.h"
#include "utilities/WeakReference.h"
#include "utilities/ControlBlock.h"
#include "utilities/Heap.h"
#include "utilities/App_05cab6792dacd661.h"
#include "accessibility/XamlMetaDataProviderActivationFactory.h"
#include "utilities/abi_dtor_helper.h"
#include "utilities/Details_8ba17485ccb117e0.h"
#include "utilities/Guid.h"
#include "utilities/StringReference.h"
#include "utilities/abi_CapturePtr.h"
#include "utilities/App_2e4461bf60644600.h"
#include "utilities/ShellExperience.h"
#include "utilities/ThreadPool.h"
#include "utilities/Application.h"
#include "utilities/TypeName.h"
#include "parsing/XmlnsDefinition.h"
#include "utilities/ExtensionFactory.h"
#include "utilities/XamlExtensions.h"
#include "utilities/CriticalSection.h"
#include "utilities/AutoLock.h"
